Repository rango-exchange/rango-client, pull requests merged in 2024-05, with the labels that each got.

#708 feat: clean solana signer simulation errors
  signers/signer-solana/src/utils/simulate.ts
Labels: need in next release

#706 feat: add more predefined fonts list from google fonts
  widget/embedded/public/index.css
  widget/embedded/public/index.html
  widget/embedded/src/constants/fonts.ts
  widget/embedded/src/containers/WidgetProvider/WidgetProvider.tsx
  widget/embedded/src/globalStyles.ts
  widget/embedded/src/hooks/useBootstrap/useBootstrap.ts
  widget/embedded/src/hooks/useFontLoader.ts
  widget/embedded/src/hooks/useTheme.ts
  widget/embedded/src/index.ts
  widget/embedded/src/types/config.ts
  widget/embedded/src/utils/common.ts
  widget/embedded/src/utils/configs.ts
  widget/playground/src/constants/fonts.ts
  widget/playground/src/constants/index.ts
  widget/playground/src/containers/StyleLayout/StyleLayout.General.tsx
  widget/playground/src/globalStyles.ts
Labels: next release

#720 fix: excluding ledger on mobile
  wallets/provider-ledger/src/index.ts
  widget/embedded/src/hooks/useWalletList.ts
Labels: next release

#711 feat: update explorer icon and add paste to custom destination
  widget/embedded/src/components/ConfirmWalletsModal/ConfirmWallets.styles.ts
  widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx
  widget/embedded/src/components/SwapDetails/SwapDetails.tsx
  widget/ui/src/icons/Paste.tsx
  widget/ui/src/icons/RangoExplorer.tsx
  widget/ui/src/icons/index.ts
  widget/ui/svgs/resources/fill/Paste.svg
  widget/ui/svgs/resources/fill/RangoExplorer.svg
Labels: next release

#715 fix: fix the automatic selection of the connected wallets in the confirm wallets modal
  widget/embedded/src/components/ConfirmWalletsModal/ConfirmWalletsModal.tsx
  widget/embedded/src/components/ConfirmWalletsModal/WalletList.tsx
  widget/embedded/src/components/ConfirmWalletsModal/WalletList.type.ts
  widget/embedded/src/store/wallets.ts
Labels: next release

#736 feat: update our colors to new colors system
  widget/embedded/src/components/HeaderButtons/HeaderButtons.styles.ts
  widget/embedded/src/components/Quote/Quote.styles.ts
  widget/embedded/src/components/TokenList/TokenList.tsx
  widget/embedded/src/types/config.ts
  widget/embedded/src/utils/colors.ts
  widget/embedded/src/utils/ui.ts
  widget/playground/src/App.tsx
  widget/playground/src/components/Collapse/Collapse.styles.ts
  widget/playground/src/components/ItemPicker/ItemPicker.styles.ts
  widget/playground/src/components/MultiSelect/MultiSelect.styles.ts
  widget/playground/src/components/TokensPanel/TokensPanel.styles.ts
  widget/playground/src/constants/presets.ts
  widget/playground/src/containers/FunctionalLayout/FunctionalLayout.styles.ts
  widget/playground/src/containers/StyleLayout/StyleLayout.CustomColors.tsx
  widget/playground/src/containers/StyleLayout/StyleLayout.Preset.tsx
  widget/playground/src/containers/StyleLayout/StyleLayout.Themes.tsx
  widget/playground/src/containers/StyleLayout/StyleLayout.styles.ts
  widget/playground/src/containers/StyleLayout/StyleLayout.types.ts
  widget/playground/src/containers/configContainer/ConfigContainer.styles.ts
  widget/playground/src/hooks/useTheme.ts
  widget/playground/src/store/config.ts
  widget/playground/src/types.ts
  widget/playground/src/utils/colors.ts
  widget/ui/src/components/Button/Button.styles.tsx
  widget/ui/src/components/ChainToken/ChainToken.styles.ts
  widget/ui/src/components/Checkbox/Checkbox.styles.ts
  widget/ui/src/components/FullExpandedQuote/FullExpandedQuote.styles.ts
  widget/ui/src/components/QuoteTag/QuoteTag.styles.ts
  widget/ui/src/components/Radio/Radio.styles.tsx
  widget/ui/src/components/Select/Select.styles.ts
  widget/ui/src/components/Skeleton/Skeleton.styles.ts
  widget/ui/src/components/Switch/Switch.styles.tsx
  widget/ui/src/components/Wallet/Wallet.styles.ts
  widget/ui/src/containers/SwapInput/SwapInput.styles.ts
  widget/ui/src/theme.ts
Labels: scope: widget
